"""Updated the tasklist table

Revision ID: 20161d94e93f
Revises: 853d0c93f051
Create Date: 2018-01-30 16:31:26.015400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20161d94e93f'
down_revision = '853d0c93f051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_list', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_list', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_list', type_='foreignkey')
    op.drop_column('task_list', 'user_id')
    # ### end Alembic commands ###
