"""TaskList table 

Revision ID: 853d0c93f051
Revises: e4264c4e358b
Create Date: 2018-01-30 16:21:03.800531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853d0c93f051'
down_revision = 'e4264c4e358b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_list_title'), 'task_list', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_list_title'), table_name='task_list')
    op.drop_table('task_list')
    # ### end Alembic commands ###
